#include <pic32mx.h>

#define DISPLAY_VBATT_PORT PORTF
#define DISPLAY_VBATT_MASK 0x20

#define DISPLAY_RESET_PORT PORTG
#define DISPLAY_RESET_MASK 0x200

#define DISPLAY_COMMAND_DATA_PORT PORTF
#define DISPLAY_COMMAND_DATA_MASK 0x10

#define DISPLAY_VDD_PORT PORTF
#define DISPLAY_VDD_MASK 0x40

#define DISPLAY_COMMAND_DATA_PORT PORTF
#define DISPLAY_COMMAND_DATA_MASK 0x10

void init(void);
void update(void);
